-- NBA Predictor Database Schema
-- This schema implements the exact data model as per the PRD

-- Teams table
CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    nba_team_id INTEGER UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    abbreviation VARCHAR(5) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Players table
CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    nba_player_id INTEGER UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    current_team_id INTEGER REFERENCES teams(id),
    position VARCHAR(10),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Matches table
CREATE TABLE IF NOT EXISTS matches (
    id SERIAL PRIMARY KEY,
    nba_game_id VARCHAR(50) UNIQUE NOT NULL,
    game_date DATE NOT NULL,
    game_time TIMESTAMP NOT NULL,
    home_team_id INTEGER REFERENCES teams(id),
    away_team_id INTEGER REFERENCES teams(id),
    season VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for matches
CREATE INDEX IF NOT EXISTS idx_game_date ON matches(game_date);
CREATE INDEX IF NOT EXISTS idx_status ON matches(status);

-- Player game stats (historical - last 15 team games)
CREATE TABLE IF NOT EXISTS player_game_stats (
    id SERIAL PRIMARY KEY,
    player_id INTEGER REFERENCES players(id) NOT NULL,
    match_id INTEGER REFERENCES matches(id) NOT NULL,
    team_id INTEGER REFERENCES teams(id) NOT NULL,
    game_date DATE NOT NULL,
    opponent_team_id INTEGER REFERENCES teams(id),
    minutes_played INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    rebounds INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    is_imputed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(player_id, match_id)
);

-- Indexes for player_game_stats
CREATE INDEX IF NOT EXISTS idx_player_date ON player_game_stats(player_id, game_date DESC);
CREATE INDEX IF NOT EXISTS idx_team_date ON player_game_stats(team_id, game_date DESC);

-- Player status (injury/out information)
CREATE TABLE IF NOT EXISTS player_status (
    id SERIAL PRIMARY KEY,
    player_id INTEGER REFERENCES players(id) NOT NULL,
    match_id INTEGER REFERENCES matches(id) NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(255),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(player_id, match_id)
);

-- Predictions (generated by prediction engine)
CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    player_id INTEGER REFERENCES players(id) NOT NULL,
    match_id INTEGER REFERENCES matches(id) NOT NULL,
    prediction_date TIMESTAMP DEFAULT NOW(),
    points_threshold INTEGER,
    rebounds_threshold INTEGER,
    assists_threshold INTEGER,
    games_analyzed INTEGER DEFAULT 15,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(player_id, match_id)
);

-- Index for predictions
CREATE INDEX IF NOT EXISTS idx_match_predictions ON predictions(match_id);

-- Prediction accuracy (admin only - post-match verification)
CREATE TABLE IF NOT EXISTS prediction_accuracy (
    id SERIAL PRIMARY KEY,
    prediction_id INTEGER REFERENCES predictions(id) NOT NULL,
    player_id INTEGER REFERENCES players(id) NOT NULL,
    match_id INTEGER REFERENCES matches(id) NOT NULL,
    points_predicted INTEGER,
    points_actual INTEGER,
    points_result VARCHAR(10),
    rebounds_predicted INTEGER,
    rebounds_actual INTEGER,
    rebounds_result VARCHAR(10),
    assists_predicted INTEGER,
    assists_actual INTEGER,
    assists_result VARCHAR(10),
    verified_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(prediction_id)
);

-- Data refresh log (track ingestion jobs)
CREATE TABLE IF NOT EXISTS data_refresh_log (
    id SERIAL PRIMARY KEY,
    refresh_date DATE NOT NULL,
    refresh_timestamp TIMESTAMP DEFAULT NOW(),
    games_fetched INTEGER DEFAULT 0,
    stats_fetched INTEGER DEFAULT 0,
    players_updated INTEGER DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);
